Update example
bastianhjaeger/github_actions_gtest_example pull request #3
Opened 2022-03-01 18:44 UTC by Lecrapouille

2022-03-01 21:37 UTC, bastianhjaeger commented
Thanks for your contribution!

I added a PR with 2 additional commits for fixing the MAcOS build issue here
https://github.com/bastianhjaeger/github_actions_gtest_example/pull/4

Note:
- You can see in the install step `Download, configure and install gtest` where the libs are installed to:
```
-- Installing: /usr/local/lib/libgtest.a
-- Installing: /usr/local/lib/libgtest_main.a
-- Installing: /usr/local/lib/pkgconfig/gtest.pc
-- Installing: /usr/local/lib/pkgconfig/gtest_main.pc
```
Hence I added this path to the cmake. On linux this path is used by default. On MacOS apparently not.

I will leave some more comments next on the code.

2022-03-01 21:49 UTC, bastianhjaeger requested changes
Thanks! Looking forward for this.

2022-03-01 21:49 UTC, bastianhjaeger commented on src/github_actions_gtest_example.cpp
> +#include "github_actions_gtest_example/github_actions_gtest_example.h"
Please revert. Not part of the PR issue.

2022-03-01 21:49 UTC, bastianhjaeger commented on src/info.cpp
> +#include "github_actions_gtest_example/github_actions_gtest_example.h"
Please revert. Not part of the PR issue.

2022-03-01 21:49 UTC, bastianhjaeger commented on test/github_actions_gtest_exampleTest.cpp
> +#include "github_actions_gtest_example/github_actions_gtest_example.h"
Please revert. Not part of the PR issue.

2022-03-01 21:49 UTC, bastianhjaeger commented on test/AllTests.cpp
> +#include <gmock/gmock.h>
Why bringing in gmock everywhere? Seems not to be needed, right? 
I probably do not mind, but I am curious.

2022-03-02 09:30 UTC, Lecrapouille commented on src/github_actions_gtest_example.cpp
> +#include "github_actions_gtest_example/github_actions_gtest_example.h"
Yes not part of the PR, you're right but also no because do you really want searching your own include in system paths first ? This makes sense for library for example. Have you already reverted on your patch ?

2022-03-02 09:30 UTC, Lecrapouille commented on test/AllTests.cpp
> +#include <gmock/gmock.h>
ok. I did not reaaly look at your gtest code. My main looks like:
```
#include <gtest/gtest.h>
// #include <gmock/gmock.h>

int main(int argc, char *argv[])
{
    // The following line must be executed to initialize Google Mock
    // (and Google Test) before running the tests.
    ::testing::InitGoogleMock(&argc, argv);

    return RUN_ALL_TESTS();
}
```

2022-03-02 09:34 UTC, Lecrapouille commented
@bastianhjaeger `Hence I added this path to the cmake.` Good news, I spent hours not finding how to set this information, I'm not feeling comfortable with CMake. So I cancel this PR and let you commit your own PR ?

2022-05-12 17:33 UTC, closed without merging